language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - source

#rvm:
#- 2.2.3

before_script:
 - chmod +x ./bin/deploy
# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./bin/deploy
exclude: [vendor]
sudo: false
